plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    //API
    testImplementation("io.rest-assured:rest-assured:6.0.1")
    testImplementation 'io.rest-assured:json-schema-validator:6.0.1'

    //JSON
    testImplementation("org.json:json:20260522")

    //Cucumber
    testImplementation 'io.cucumber:cucumber-java:7.34.6'
    testImplementation 'io.cucumber:cucumber-junit:7.34.6'

    //JUnit
    testImplementation 'junit:junit:4.13.2'

    //Selenium
    testImplementation 'org.seleniumhq.selenium:selenium-java:4.46.0'
}

configurations {
    cucumberRuntime {
        extendsFrom testImplementation
    }
}

def tags = (findProperty('tags') == null) ? 'not @exclude' : findProperty('tags') + ' and not @exclude'

tasks.register("apiCucumber", JavaExec) {
    description = "Running API Test"
    dependsOn assemble, compileTestJava
    classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
    mainClass = "io.cucumber.core.cli.Main"
    args = [
            '--plugin', 'html:reports/api/api-report.html',
            '--plugin', 'json:reports/api/api-report.html',
            '--plugin', 'pretty',
            '--glue', 'api',
            '--tags', "@api",
            'src/test/resources/api'
    ]

}

tasks.register("webCucumber", JavaExec) {
    description = "Running Web UI Test"
    dependsOn assemble, compileTestJava
    classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
    mainClass = "io.cucumber.core.cli.Main"
    args = [
            '--plugin', 'html:reports/web/ui-report.html',
            '--plugin', 'json:reports/web/ui-report.html',
            '--plugin', 'pretty',
            '--glue', 'webui',
            '--tags', "@web",
            'src/test/resources/webui'
    ]
}